SELECT
    A.AUTHOR_ID             AS AUTHOR_ID,
    B.AUTHOR_NAME           AS AUTHOR_NAME,
    A.CATEGORY              AS CATEGORY,
    SUM(A.PRICE * C.SALES)  AS TOTAL_SALES
FROM
    BOOK A
    JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE
    C.SALES_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD')
                     AND TO_DATE('2022-01-31', 'YYYY-MM-DD')
GROUP BY
    A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY
    A.AUTHOR_ID ASC, A.CATEGORY DESC;