-- 코드를 입력하세요
SELECT  EXTRACT(YEAR FROM B.SALES_DATE) YEAR,
        EXTRACT(MONTH FROM B.SALES_DATE) MONTH,
        A.GENDER GENDER,
        COUNT(DISTINCT A.USER_ID) USERS
FROM    USER_INFO A,
        ONLINE_SALE B
WHERE   A.USER_ID = B.USER_ID
    AND A.GENDER IS NOT NULL
GROUP BY
        EXTRACT(YEAR FROM B.SALES_DATE),
        EXTRACT(MONTH FROM B.SALES_DATE),
        A.GENDER
ORDER BY YEAR ASC, MONTH ASC, A.GENDER ASC