-- 코드를 작성해주세요
SELECT COUNT(INFO.ID) AS FISH_COUNT, NAME_INFO.FISH_NAME
FROM FISH_INFO AS INFO
    JOIN FISH_NAME_INFO AS NAME_INFO
    ON INFO.FISH_TYPE = NAME_INFO.FISH_TYPE
GROUP BY NAME_INFO.FISH_NAME
ORDER BY FISH_COUNT DESC