-- 코드를 입력하세요
SELECT HALF.FLAVOR
FROM ICECREAM_INFO INFO 
    JOIN FIRST_HALF HALF
    ON INFO.FLAVOR = HALF.FLAVOR
WHERE HALF.TOTAL_ORDER >= 3000
    AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY HALF.TOTAL_ORDER DESC