-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, GR.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_GRADE AS GR
    JOIN HR_EMPLOYEES AS EM
    ON GR.EMP_NO = EM.EMP_NO
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1
